package com.interviewos.api.interview

import com.interviewos.api.interview.PoolFixtures.question
import com.interviewos.api.pool.Association
import com.interviewos.api.pool.Level
import com.interviewos.api.pool.RoleFamily
import org.junit.jupiter.api.Test
import java.time.Instant
import java.util.UUID
import kotlin.random.Random
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/** The label a pool question carries, verbatim, and that nothing sourced ever carries it. */
class PoolQuestionLabelTest {
    private val amazon = BankFixtures.amazon

    @Test
    fun `a company-specific question for this company names it`() {
        val q =
            question(
                "Tell me about a time you owned a customer problem end to end.",
                association = Association.COMPANY_SPECIFIC,
                knowledgeBasis = "Publishes its leadership principles.",
            )

        assertEquals(
            "Generated by our AI interviewer from general knowledge. Not a verified report of a question Amazon asked.",
            PoolQuestionLabel.of(q, amazon),
        )
    }

    @Test
    fun `an employer-kind question names the kind of employer and never the employer`() {
        val q = question("Tell me about a time you disagreed with a senior colleague.", archetype = Archetype.SERVICE_BASED_IT)

        val label = PoolQuestionLabel.of(q, amazon)

        assertEquals(
            "Generated by our AI interviewer from general knowledge. Not a verified report of a question asked at a service-based IT firm.",
            label,
        )
        assertFalse(label.contains("Amazon"))
    }

    @Test
    fun `a company-specific claim reads as the kind of employer unless it is this company's and has a basis`() {
        val elsewhere =
            question("Q", companyId = UUID.randomUUID(), association = Association.COMPANY_SPECIFIC, knowledgeBasis = "Knows it.")
        val noBasis = question("Q", association = Association.COMPANY_SPECIFIC, knowledgeBasis = " ")
        val archetypeRow = question("Q", companyId = null, association = Association.COMPANY_SPECIFIC, knowledgeBasis = "Knows it.")
        val kind = PoolQuestionLabel.employerKind(Archetype.GLOBAL_PRODUCT)

        assertEquals(kind, PoolQuestionLabel.of(elsewhere, amazon))
        assertEquals(kind, PoolQuestionLabel.of(noBasis, amazon))
        assertEquals(kind, PoolQuestionLabel.of(archetypeRow, amazon))
        assertEquals(
            kind,
            PoolQuestionLabel.of(question("Q", association = Association.COMPANY_SPECIFIC, knowledgeBasis = "Knows it."), null),
        )
    }

    @Test
    fun `every archetype has a noun phrase with its article`() {
        Archetype.entries.forEach { assertTrue(Regex("^an? [A-Za-z]").containsMatchIn(PoolQuestionLabel.kindOf(it)), it.name) }
    }

    @Test
    fun `a pool question is model knowledge with its label, and a sourced question never carries either label`() {
        val pooled = QuestionProvenance.fromPool(PoolQuestionLabel.companySpecific("Amazon"), "Ownership.", null)
        assertEquals(ProvenanceTier.MODEL_KNOWLEDGE, pooled.tier)
        assertTrue(pooled.sources.isEmpty())
        assertEquals("", pooled.basis)

        val sourced =
            assertNotNull(QuestionProvenance.fromBank(BankFixtures.question("Tell me about a time you failed."), "Amazon", null, null))
        val modelOwn = assertNotNull(QuestionProvenance.fromModel("Behavioural rounds ask this.", "Ownership.", "You mentioned it."))
        listOf(sourced, modelOwn).forEach { provenance ->
            assertNull(provenance.label)
            val rendered =
                listOf(
                    provenance.basis,
                    provenance.tier.disclosure,
                    provenance.probes,
                    provenance.askedBecause,
                ).joinToString(" ")
            assertFalse(rendered.contains(PoolQuestionLabel.GENERATED), rendered)
            assertFalse(rendered.contains("Not a verified report"), rendered)
        }
        assertEquals(ProvenanceTier.PUBLISHED_SOURCE, sourced.tier)
    }
}

/** Which pool question a round asks next, and that none is ever asked twice. */
class PoolQuestionSelectionTest {
    private val amazon = BankFixtures.amazon
    private val atLevel = question("At level", level = Level.MID)
    private val below = question("Below", level = Level.ENTRY)
    private val above = question("Above", level = Level.SENIOR)
    private val archetypeRow = question("Archetype", companyId = null, level = Level.MID)
    private val otherCompany = question("Other company", companyId = UUID.randomUUID(), level = Level.MID)
    private val otherArchetype = question("Other archetype", companyId = null, archetype = Archetype.SERVICE_BASED_IT)

    private fun round(vararg questions: com.interviewos.api.pool.PoolQuestion) =
        PoolRound(
            amazon,
            Archetype.GLOBAL_PRODUCT,
            Level.MID,
            PoolQuestionSelection.rank(questions.toList(), amazon.id, Archetype.GLOBAL_PRODUCT, Level.MID),
        )

    @Test
    fun `this company at the level, then the nearest level lower first, then the archetype rows`() {
        val ranked = round(archetypeRow, above, below, atLevel).questions

        assertEquals(listOf(atLevel, below, above, archetypeRow), ranked)
    }

    @Test
    fun `another company's rows and another archetype's are never offered`() {
        assertEquals(listOf(archetypeRow), round(otherCompany, otherArchetype, archetypeRow).questions)
        assertNull(PoolQuestionSelection.tierOf(otherCompany, amazon.id, Archetype.GLOBAL_PRODUCT, Level.MID))
    }

    @Test
    fun `an unknown employer gets the archetype rows only`() {
        val ranked = PoolQuestionSelection.rank(listOf(atLevel, archetypeRow), null, Archetype.GLOBAL_PRODUCT, Level.MID)

        assertEquals(listOf(archetypeRow), ranked)
    }

    @Test
    fun `draws only from the best tier with anything fresh in it`() {
        val drawn = (0 until 20).map { choose(round(atLevel, below, archetypeRow), random = Random(it)) }.toSet()

        assertEquals(setOf(atLevel), drawn)
    }

    @Test
    fun `a question this candidate was asked in an earlier round is not offered again`() {
        val chosen = choose(round(atLevel, below), lastAsked = mapOf(atLevel.id to Instant.now()))

        assertEquals(below, chosen)
    }

    @Test
    fun `when every question has been asked the pool offers nothing rather than a repeat`() {
        val asked = mapOf(atLevel.id to Instant.parse("2026-01-01T00:00:00Z"), archetypeRow.id to Instant.now())

        assertNull(choose(round(atLevel, archetypeRow), lastAsked = asked))
    }

    @Test
    fun `a question asked in this round never comes back in it`() {
        assertNull(choose(round(atLevel), askedThisRound = setOf(atLevel.id)))
    }

    private fun choose(
        round: PoolRound,
        lastAsked: Map<UUID, Instant> = emptyMap(),
        askedThisRound: Set<UUID> = emptySet(),
        random: Random = Random(0),
    ) = PoolQuestionSelection.choose(round, lastAsked + askedThisRound.associateWith { Instant.now() }, askedThisRound, random)
}

/** The pool coordinate a session reads from. */
class PoolRoundCoordinateTest {
    @Test
    fun `engineering titles map to a family, and a role the pool is not written for maps to none`() {
        assertEquals(RoleFamily.BACKEND, PoolRoundCoordinate.roleFamily("SDE 2"))
        assertEquals(RoleFamily.BACKEND, PoolRoundCoordinate.roleFamily("Systems Engineer"))
        assertEquals(RoleFamily.QA_AUTOMATION, PoolRoundCoordinate.roleFamily("SDET"))
        assertEquals(RoleFamily.MOBILE, PoolRoundCoordinate.roleFamily("React Native developer"))
        assertEquals(RoleFamily.FULLSTACK_FRONTEND, PoolRoundCoordinate.roleFamily("Full-stack Java developer"))
        assertEquals(RoleFamily.ML_AI, PoolRoundCoordinate.roleFamily("ML Engineer"))
        assertEquals(RoleFamily.DATA_ENGINEERING, PoolRoundCoordinate.roleFamily("Senior Data Engineer"))
        assertEquals(RoleFamily.SRE, PoolRoundCoordinate.roleFamily("DevOps engineer"))
        listOf("Product Manager", "Data Analyst", "Chartered Accountant", "Engineering Manager", "Consultant").forEach {
            assertNull(PoolRoundCoordinate.roleFamily(it), it)
        }
    }

    @Test
    fun `the title decides the level when it says, and the resume when it does not`() {
        assertEquals(Level.MID, PoolRoundCoordinate.level("SDE 2", experienceMonths = 120))
        assertEquals(Level.ENTRY, PoolRoundCoordinate.level("SDE-I", null))
        assertEquals(Level.SENIOR, PoolRoundCoordinate.level("Senior Software Engineer", 12))
        assertEquals(Level.STAFF, PoolRoundCoordinate.level("Principal Engineer", null))
        assertEquals(Level.MID, PoolRoundCoordinate.level("Member of Technical Staff", null))
        assertEquals(Level.ENTRY, PoolRoundCoordinate.level("Software Engineer", 10))
        assertEquals(Level.SENIOR, PoolRoundCoordinate.level("Software Engineer", 84))
        assertEquals(Level.MID, PoolRoundCoordinate.level("Software Engineer", null))
    }
}

/** A pool question's payload, read back into a workspace's material. */
class PoolMaterialTest {
    private val material = PoolMaterial(PoolFixtures.mapper)

    @Test
    fun `a verified coding payload is the problem, with its tests and no solution`() {
        val problem =
            assertNotNull(
                material.problemOf(
                    question("Longest substring", roundType = RoundType.CODING_PRACTICAL, payload = PoolFixtures.codingPayload()),
                ),
            )

        assertTrue(problem.testsVerified)
        assertEquals(listOf("abcabcbb" to "3", "bbbbb" to "1"), problem.testCases.map { it.input to it.expected })
        assertNull(problem.referencePython)
        assertNull(problem.bruteForcePython)
        assertEquals("Sliding window problem", problem.title)
    }

    @Test
    fun `an unverified, missing or mismatched payload is not usable for a coding round`() {
        val unverified = question("A", roundType = RoundType.CODING_PRACTICAL, payload = PoolFixtures.codingPayload(testsVerified = false))
        val none = question("B", roundType = RoundType.CODING_PRACTICAL)
        val wrongKind =
            question("C", roundType = RoundType.CODING_PRACTICAL, payload = PoolFixtures.mapper.readTree("""{"kind":"system_design"}"""))

        listOf(unverified, none, wrongKind).forEach { assertFalse(material.isUsable(it, RoundType.CODING_PRACTICAL), it.text) }
        assertTrue(material.isUsable(none, RoundType.BEHAVIOURAL_COMPETENCY))
    }

    @Test
    fun `a design payload is the case, opened with the question's own text`() {
        val payload =
            PoolFixtures.mapper.readTree(
                """{"kind":"system_design","designTag":"distributed_design","title":"A news feed","summary":"Design a feed.",
                   "constraints":["10M users"],"weakAnswerMisses":["fan-out"]}""",
            )
        val case =
            assertNotNull(material.caseOf(question("Let's design a news feed.", roundType = RoundType.SYSTEM_DESIGN, payload = payload)))

        assertEquals("A news feed", case.title)
        assertEquals("Let's design a news feed.", case.openingPrompt)
        assertEquals(listOf("10M users"), case.constraints)
    }
}
